#!/bin/bash
# 
# Refactored by Kimberly Lazarski in March, 2026
# Contact info: klazarsk@redhat.com
#
# Bugs fixed: Made compatible with modern builds of gnuplot 
#             Added a shebang (interpreted scripts called from 
#             a shell should always include a shebang so it runs
#             even for users who use tcsh or other oddball shells!)
#
# Features added: 
#  - Flexible command line options
#    - Made pathing arbitrary
#    - enabled ability to adapt to alternate install locations
#    - Added help screen
#
# This script will create the Iozone graphs using
# gnuplot. 
#
# ------------------------------------------------
# YOU MUST PROVIDE A FILE NAME FOR IT TO PROCESS.
# This filename is the name of the file where you 
# sent Iozone's output.
# ------------------------------------------------

dirWorking="${PWD}"

# if the config file exists, source it; it is expected to be 
# a bash file to set up environment variables. Maybe change 
# to .ini format later? 

if [ -d /etc/iozone.conf ];
then
  source /etc/iozone.conf
else
  dirIozone="/opt/iozone"
fi
dirIozoneBin="${dirIozone}/bin"

#########################
#
# Setting formatting tags
otagBold="\e[1m";
ctag="\e[0m";
otagRed='\e[0;31m';
otagRevRed='\e[0;101m';
otagUline="\e[4m";
otagItal="\e[3m";
###############################
#
cmdDate='date +%Y-%m-%d_%H:%M:%S';
cmdDbgEcho="true";
cmdDbgRead="true";
cmdDbgSleep="true";
cmdDbgAnyKey="true";
cmdAnyKey='read -n 1 -s -r -p "Press any key to continue..."'

#
# Function Definitions

fnHelp() {
  # This is the help screen
  echo "This will be a help screen. Honest!"
}


###############################
# Since user gave us stuff to do, let's process arguments. Party on!
while [ "${1}" != "" ] ;
do 
  case ${1} in
    -h | --help )   fnHelp;
                    exit 0;
                    ;;
    -D | --debug ) optDebug=1;
                    cmdDbgRead="read";
                    cmdDbgSleep="sleep";
                    cmdDbgEcho="echo";
                    cmdDbgAnyKey='eval read -n 1 -s -r -p "Debug mode: Press any key to continue..."'
                    ;;
    -i | "--input"* ) if [[ "${1}" != *'='* ]]; then shift; fi
                   fileInput="${1##*=}"
                   ;;
    -w | "--working-dir"* ) if [[ "${1}" != *'='* ]]; then shift; fi
                   dirWorking="${1##*=}"
                   ;;
  esac ;
  shift ;
done;

###############################
# Sanity checks
#



#
###############################

${cmdDbgEcho} "strIozone=${dirIozone}"
${cmdDbgEcho} "strIozoneBin=${dirIozoneBin}"
${cmdDbgEcho} "fileInput=${fileInput}"
${cmdDbgEcho} "dirWorking=${dirWorking}"
${cmdDbgAnyKey}

if [[ "${dirWorking}" != "${PWD}" ]]; 
then
  if [ ! -d "${dirWorking}" ]; 
  then
    echo "ERROR: the specified --working-dir ${dirWorking} does not exist."
    exit 1
  fi;
  pushd "${dirWorking}";
  ${cmdDebugEcho} "${LINENO}: Switched to ${PWD} which should be ${dirWorking}"
fi

# Generate data base for all of the operation types.

"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" write
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" rewrite
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" read
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" reread
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" randread
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" randwrite
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" bkwdread
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" recrewrite
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" strideread
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" fwrite
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" frewrite
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" fread
"${dirIozoneBin}/gengnuplot.sh" "${fileInput}" freread

# Produce graphs and postscript results.
gnuplot "${dirIozoneBin}/gnu3d.dem"

if [[ "$(dirs -0)" != "${PWD}" ]];
then
  popd; 
fi;
